
#*********************Choose Environment************************#
# ENV = "SIT1"
ENV = "UAT"
# ENV = "SIT2"
# ENV = "PA"
# ENV = "UAT"
# ENV = "HF"



#*********************Set ENV For DB************************#
if ENV == "SIT1" or ENV == "P1":
    ENV = "SIT1"
elif ENV == "SIT2" or ENV == "PA":
    ENV = "SIT2"
elif ENV == "SIT3" or ENV == "HF":
    ENV = "SIT3"
elif ENV == "UAT" or ENV == "T4":
    ENV = "UAT"    

#***************ChromeDriverPath***************#
Chrome_Driver_Folder_Location = "T:\\IT\\QAT\\QC\\CGI_E2EAutomation\\WebDrivers"

#*********************DB Details************************#
DB_SIT_USER_NAME = "SMALLSIT"
DB_SIT_PASSWORD = "Welcome123"
DB_SIT_HOST_NAME = "172.26.25.224"
DB_SIT_PORT_NUMBER = 1544
DB_SIT_SERVICE_NAME = "DEVDMLA"
DB_UAT_USER_NAME = "SMALLUAT"
DB_UAT_PASSWORD = "Welcome123"
DB_UAT_HOST_NAME = "CB2423799.DCC.CLOUD1.CIBC.COM"
DB_UAT_PORT_NUMBER = 1615
DB_UAT_SERVICE_NAME = "UATDMLA"
DB_SCHEMA_DMRTL = "DMRTL_"+ENV+"3"
DB_SCHEMA_CWL = "CWL_"+ENV
DB_ADJ_APP = "ADJ_APP"
DB_SECURITY_REA = "SECURITY_REA"
DB_Application = "APPLICATION"
DB_Applicant = "APPLICANT"
DB_INSURER_FEED_DATA = "INSURER_FEED_DATA"
DB_CLASS_NUM = "CLASS_NUM"
DB_TDSR = "TDSR"
DB_GDSR = "GDSR"
DB_LOAN_TO_VALUE = "LOAN_TO_VALUE"
DB_REV_LTV = "REV_LTV"
DB_APPRAISAL_VALUE = "APPRAISAL_VALUE"
DB_PAYMENT_FREQUENCY = "PAYMENT_FREQUENCY"
DB_AMORTIZATION_PERIOD = "AMORTIZATION_PERIOD"
DB_TOTAL_MONTHLY_INCOME = "TOTAL_MONTHLY_INCOME"
DB_PID = "PID"
DB_INTEREST_RATE_TYPE = "INTEREST_RATE_TYPE"
DB_APPSTATUSDATE = "APPSTATUSDATE"
DB_MORTGAGE_SERVICING_NUMBER = "MORTGAGE_SERVICING_NUMBER"
DB_APP_NUMBER = "APP_NUMBER"
DB_FIRST_NAME = "FIRST_NAME"
DB_LAST_NAME = "LAST_NAME"
DB_MARITAL_STATUS = "MARITAL_STATUS"
DB_CUSTOMER_TYPE = "CUSTOMER_TYPE"
DB_NUMBER_OF_DEPENDANTS = "NUMBER_OF_DEPENDANTS"
DB_LANGUAGE = "LANGUAGE"
DB_DOB = "DOB"
DB_MOBILE_NUMBER = "MOBILE_NUMBER"
DB_HOME_PHONE = "HOME_PHONE"
DB_DISBURSEMENT_DATE = "DISBURSEMENT_DATE"
DB_PAYMENT_TYPE = "PAYMENT_TYPE"
DB_LOOKBACK_TYPE = "LOOKBACK_TYPE"
DB_ADDL_APPL_DETAILS = "ADDL_APPL_DETAILS"
DB_CASE_ID = "CASE_ID"
DB_RENEGOTIATED_INDICATOR = "RENEGOTIATED_INDICATOR"
DB_CLASS_REQUEST_CLOB = "CLASS_REQUEST_CLOB"
DB_ADJ_REQUEST_CLOB = "ADJ_REQUEST_CLOB"
DB_ADJ_PERCUST = "ADJ_PERCUST"
DB_BEACON_EMPIRICA_SCORE = "BEACON_EMPIRICA_SCORE"
ORACLE_CLIENT_32_DEPENDECY = "T:\\IT\\Tools\\RobotFramework_Pkg\\Oracle_Dependency_Python\\oracle_client_dependency_32_bit\\instantclient_21_3"
ORACLE_CLIENT_64_DEPENDECY = "T:\\IT\\Tools\\RobotFramework_Pkg\\Oracle_Dependency_Python\\oracle_client_dependency_64_bit\\instantclient_21_3"
iMin = "5s"


#*********************Set ENV************************#
if ENV == "SIT1" or ENV == "P1":
    DB_USER_NAME = DB_SIT_USER_NAME
    DB_PASSWORD = DB_SIT_PASSWORD
    DB_HOST_NAME = DB_SIT_HOST_NAME
    DB_PORT_NUMBER = DB_SIT_PORT_NUMBER
    DB_SERVICE_NAME = DB_SIT_SERVICE_NAME
elif ENV == "SIT2" or ENV == "PA":
    DB_USER_NAME = DB_SIT_USER_NAME
    DB_PASSWORD = DB_SIT_PASSWORD
    DB_HOST_NAME = DB_SIT_HOST_NAME
    DB_PORT_NUMBER = DB_SIT_PORT_NUMBER
    DB_SERVICE_NAME = DB_SIT_SERVICE_NAME
elif ENV == "UAT" or ENV == "T4":
    DB_USER_NAME = DB_UAT_USER_NAME
    DB_PASSWORD = DB_UAT_PASSWORD
    DB_HOST_NAME = DB_UAT_HOST_NAME
    DB_PORT_NUMBER = DB_UAT_PORT_NUMBER
    DB_SERVICE_NAME = DB_UAT_SERVICE_NAME


#*********************Reflection************************#
REFLECTION_SESSION_NAME = "Session2.rd5x"
REFLECTION_SESSION_FOLDER = "C:\\ProgramData\\Microfocus\\Reflection\\Sessions"
REFLECTION_PROGRAM_NAME = "C:\\Program Files (x86)\\Micro Focus\\Reflection\\Attachmate.Emulation.Frame.exe"



