WITH WeekData AS 
    (SELECT resource_name,resource_id, DATE(start_date) AS start_date, 
    DATE(end_date) AS end_date, 
    (weekly_allocation_on_project / 100.0) AS weekly_allocation,
    DATE_FORMAT( start_date,'%Y-%m') AS month  FROM resources_allocation),
MonthlyUtilization AS 
    (SELECT resource_name, month,resource_id, 
    sum(weekly_allocation)/(count(distinct start_date)) AS monthly_utilization 
    FROM WeekData GROUP BY resource_name, month,resource_id),
tmp_cte_1 as 
    ( SELECT resources.name, resources.company_name, 
    resources.location,resources.resource_additional_info,MonthlyUtilization.month,
    round(MonthlyUtilization.monthly_utilization,3) as monthly_utilization 
    FROM MonthlyUtilization left join resources on 
    resources.resource_id = MonthlyUtilization.resource_id
     ORDER BY resource_name, month )
select name, company_name,location,resource_additional_info,

     sum(case when month = '2022-01' then monthly_utilization else 0 end) as 'Jan-22',
     sum(case when month = '2022-02' then monthly_utilization else 0 end) as 'Feb-22',
     sum(case when month = '2022-03' then monthly_utilization else 0 end) as 'Mar-22',
     sum(case when month = '2022-04' then monthly_utilization else 0 end) as 'Apr-22',
     sum(case when month = '2022-05' then monthly_utilization else 0 end) as 'May-22',
     sum(case when month = '2022-06' then monthly_utilization else 0 end) as 'Jun-22',
     sum(case when month = '2022-07' then monthly_utilization else 0 end) as 'Jul-22',
     sum(case when month = '2022-08' then monthly_utilization else 0 end) as 'Aug-22',
     sum(case when month = '2022-09' then monthly_utilization else 0 end) as 'Sep-22',
     sum(case when month = '2022-10' then monthly_utilization else 0 end) as 'Oct-22',
     sum(case when month = '2022-11' then monthly_utilization else 0 end) as 'Nov-22',
     sum(case when month = '2022-12' then monthly_utilization else 0 end) as 'Dec-22',
     sum(case when month = '2023-01' then monthly_utilization else 0 end) as 'Jan-23',
     sum(case when month = '2023-02' then monthly_utilization else 0 end) as 'Feb-23',
     sum(case when month = '2023-03' then monthly_utilization else 0 end) as 'Mar-23',
     sum(case when month = '2023-04' then monthly_utilization else 0 end) as 'Apr-23',
     sum(case when month = '2023-05' then monthly_utilization else 0 end) as 'May-23',
     sum(case when month = '2023-06' then monthly_utilization else 0 end) as 'Jun-23',
     sum(case when month = '2023-07' then monthly_utilization else 0 end) as 'Jul-23',
     sum(case when month = '2023-08' then monthly_utilization else 0 end) as 'Aug-23',
     sum(case when month = '2023-09' then monthly_utilization else 0 end) as 'Sep-23',
     sum(case when month = '2023-10' then monthly_utilization else 0 end) as 'Oct-23',
     sum(case when month = '2023-11' then monthly_utilization else 0 end) as 'Nov-23',
     sum(case when month = '2023-12' then monthly_utilization else 0 end) as 'Dec-23',
     sum(case when month = '2024-01' then monthly_utilization else 0 end) as 'Jan-24',
     sum(case when month = '2024-02' then monthly_utilization else 0 end) as 'Feb-24',
     sum(case when month = '2024-03' then monthly_utilization else 0 end) as 'Mar-24',
     sum(case when month = '2024-04' then monthly_utilization else 0 end) as 'Apr-24',
     sum(case when month = '2024-05' then monthly_utilization else 0 end) as 'May-24',
     sum(case when month = '2024-06' then monthly_utilization else 0 end) as 'Jun-24',
     sum(case when month = '2024-07' then monthly_utilization else 0 end) as 'Jul-24',
     sum(case when month = '2024-08' then monthly_utilization else 0 end) as 'Aug-24',
     sum(case when month = '2024-09' then monthly_utilization else 0 end) as 'Sep-24',
     sum(case when month = '2024-10' then monthly_utilization else 0 end) as 'Oct-24',
     sum(case when month = '2024-11' then monthly_utilization else 0 end) as 'Nov-24',
     sum(case when month = '2024-12' then monthly_utilization else 0 end) as 'Dec-24',
     sum(case when month = '2025-01' then monthly_utilization else 0 end) as 'Jan-25',
     sum(case when month = '2025-02' then monthly_utilization else 0 end) as 'Feb-25',
     sum(case when month = '2025-03' then monthly_utilization else 0 end) as 'Mar-25',
     sum(case when month = '2025-04' then monthly_utilization else 0 end) as 'Apr-25',
     sum(case when month = '2025-05' then monthly_utilization else 0 end) as 'May-25',
     sum(case when month = '2025-06' then monthly_utilization else 0 end) as 'Jun-25',
     sum(case when month = '2025-07' then monthly_utilization else 0 end) as 'Jul-25',
     sum(case when month = '2025-08' then monthly_utilization else 0 end) as 'Aug-25',
     sum(case when month = '2025-09' then monthly_utilization else 0 end) as 'Sep-25',
     sum(case when month = '2025-10' then monthly_utilization else 0 end) as 'Oct-25',
     sum(case when month = '2025-11' then monthly_utilization else 0 end) as 'Nov-25',
     sum(case when month = '2025-12' then monthly_utilization else 0 end) as 'Dec-25',
     sum(case when month = '2026-01' then monthly_utilization else 0 end) as 'Jan-26',
     sum(case when month = '2026-02' then monthly_utilization else 0 end) as 'Feb-26',
     sum(case when month = '2026-03' then monthly_utilization else 0 end) as 'Mar-26',
     sum(case when month = '2026-04' then monthly_utilization else 0 end) as 'Apr-26',
     sum(case when month = '2026-05' then monthly_utilization else 0 end) as 'May-26',
     sum(case when month = '2026-06' then monthly_utilization else 0 end) as 'Jun-26',
     sum(case when month = '2026-07' then monthly_utilization else 0 end) as 'Jul-26',
     sum(case when month = '2026-08' then monthly_utilization else 0 end) as 'Aug-26',
     sum(case when month = '2026-09' then monthly_utilization else 0 end) as 'Sep-26',
     sum(case when month = '2026-10' then monthly_utilization else 0 end) as 'Oct-26',
     sum(case when month = '2026-11' then monthly_utilization else 0 end) as 'Nov-26',
     sum(case when month = '2026-12' then monthly_utilization else 0 end) as 'Dec-26',
     sum(case when month = '2027-01' then monthly_utilization else 0 end) as 'Jan-27',
     sum(case when month = '2027-02' then monthly_utilization else 0 end) as 'Feb-27',
     sum(case when month = '2027-03' then monthly_utilization else 0 end) as 'Mar-27',
     sum(case when month = '2027-04' then monthly_utilization else 0 end) as 'Apr-27',
     sum(case when month = '2027-05' then monthly_utilization else 0 end) as 'May-27',
     sum(case when month = '2027-06' then monthly_utilization else 0 end) as 'Jun-27',
     sum(case when month = '2027-07' then monthly_utilization else 0 end) as 'Jul-27',
     sum(case when month = '2027-08' then monthly_utilization else 0 end) as 'Aug-27',
     sum(case when month = '2027-09' then monthly_utilization else 0 end) as 'Sep-27',
     sum(case when month = '2027-10' then monthly_utilization else 0 end) as 'Oct-27',
     sum(case when month = '2027-11' then monthly_utilization else 0 end) as 'Nov-27',
     sum(case when month = '2027-12' then monthly_utilization else 0 end) as 'Dec-27'  

from tmp_cte_1 group by name, company_name,location,resource_additional_info 
