Select RELEASE_CYCLES.RCYC_NAME as CYCLE, 
BG_SEVERITY as SEVERITY,  
BG_USER_07 as APPLICATION ,count(*) as COUNT
FROM <DB_NAME>.dbo.BUG
INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
WHERE RELEASES.REL_ID=<SelectedReleaseID> and BG_STATUS <> 'CLosed'  GROUP BY  RELEASE_CYCLES.RCYC_NAME,BG_SEVERITY ,BG_USER_07