SELECT
    O.RCYC_NAME AS CYCLE,
    O.ROOTCAUSE,
    O.SEV1,
    O.SEV2,
    O.SEV3,
    O.SEV4    
FROM
(
    SELECT
        R.RC_NUM,
        R.ROOTCAUSE,
        R.REL_ID,
        R.REL_NAME,
        R.PROJECT,
        R.REL_END_DATE,
        R.RCYC_NAME,
        COALESCE(SEV1.BUG_COUNT, 0) AS SEV1,
        COALESCE(SEV2.BUG_COUNT, 0) AS SEV2,
        COALESCE(SEV3.BUG_COUNT, 0) AS SEV3,
        COALESCE(SEV4.BUG_COUNT, 0) AS SEV4
    FROM    
    (
        SELECT
            ROOT_CAUSES.RC_NUM,
            ROOT_CAUSES.ROOTCAUSE,
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME    
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        CROSS JOIN
        (
            SELECT 1  AS RC_NUM, 'Business Requirements' AS ROOTCAUSE
                UNION ALL
            SELECT 2  AS RC_NUM, 'Code' AS ROOTCAUSE
                UNION ALL
            SELECT 3  AS RC_NUM, 'Data' AS ROOTCAUSE
                UNION ALL
            SELECT 4  AS RC_NUM, 'Design' AS ROOTCAUSE
                UNION ALL
            SELECT 5  AS RC_NUM, 'Development Documentation' AS ROOTCAUSE
                UNION ALL
            SELECT 6  AS RC_NUM, 'Duplicate' AS ROOTCAUSE
                UNION ALL
            SELECT 7  AS RC_NUM, 'Existing Production Defect' AS ROOTCAUSE
                UNION ALL
            SELECT 8  AS RC_NUM, 'Not a Variance' AS ROOTCAUSE
                UNION ALL
            SELECT 9  AS RC_NUM, 'Not Yet Analyzed' AS ROOTCAUSE
                UNION ALL
            SELECT 10 AS RC_NUM, 'Solution Requirements' AS ROOTCAUSE
                UNION ALL
            SELECT 11 AS RC_NUM, 'Technical Constraint' AS ROOTCAUSE
                UNION ALL
            SELECT 12 AS RC_NUM, 'Test Case' AS ROOTCAUSE
                UNION ALL
            SELECT 13 AS RC_NUM, 'Test Environment' AS ROOTCAUSE
		UNION ALL
            SELECT 14 AS RC_NUM, 'Content' AS ROOTCAUSE
		UNION ALL
            SELECT 15 AS RC_NUM, 'Deployment' AS ROOTCAUSE
		UNION ALL
            SELECT 16 AS RC_NUM, 'Observation' AS ROOTCAUSE
			) AS ROOT_CAUSES 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS R
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.ROOTCAUSE,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=1
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV1 ON SEV1.REL_ID=R.REL_ID AND SEV1.RCYC_NAME=R.RCYC_NAME AND SEV1.ROOTCAUSE=R.ROOTCAUSE
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.ROOTCAUSE,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=2
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV2 ON SEV2.REL_ID=R.REL_ID AND SEV2.RCYC_NAME=R.RCYC_NAME AND SEV2.ROOTCAUSE=R.ROOTCAUSE
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.ROOTCAUSE,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=3
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV3 ON SEV3.REL_ID=R.REL_ID AND SEV3.RCYC_NAME=R.RCYC_NAME AND SEV3.ROOTCAUSE=R.ROOTCAUSE
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.ROOTCAUSE,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=4
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV4 ON SEV4.REL_ID=R.REL_ID AND SEV4.RCYC_NAME=R.RCYC_NAME AND SEV4.ROOTCAUSE=R.ROOTCAUSE


    UNION ALL


    SELECT
        R.RC_NUM,
        R.ROOTCAUSE,
        R.REL_ID,
        R.REL_NAME,
        R.PROJECT,
        R.REL_END_DATE,
        R.RCYC_NAME,
        COALESCE(SEV1.BUG_COUNT, 0) AS SEV1,
        COALESCE(SEV2.BUG_COUNT, 0) AS SEV2,
        COALESCE(SEV3.BUG_COUNT, 0) AS SEV3,
        COALESCE(SEV4.BUG_COUNT, 0) AS SEV4
    FROM    
    (
        SELECT
            7 AS RC_NUM,
            'Total' AS ROOTCAUSE,
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME    
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID   
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS R
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=1
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV1 ON SEV1.REL_ID=R.REL_ID AND SEV1.RCYC_NAME=R.RCYC_NAME
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=2
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV2 ON SEV2.REL_ID=R.REL_ID AND SEV2.RCYC_NAME=R.RCYC_NAME
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=3
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV3 ON SEV3.REL_ID=R.REL_ID AND SEV3.RCYC_NAME=R.RCYC_NAME
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            B.SEVERITY,
            B.BUG_COUNT
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        LEFT JOIN
        (
            SELECT
                RELEASES.REL_ID,
                RELEASE_CYCLES.RCYC_NAME,
                LEFT(BG_SEVERITY, 1) AS SEVERITY,
                COUNT(*) AS BUG_COUNT
            FROM <DB_NAME>.dbo.BUG
            INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
            INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
            WHERE RELEASES.REL_ID=<SelectedReleaseID>
                AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
                AND LEFT(BG_SEVERITY, 1)=4
                AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
            GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
        ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS SEV4 ON SEV4.REL_ID=R.REL_ID AND SEV4.RCYC_NAME=R.RCYC_NAME
) AS O WHERE O.ROOTCAUSE <> 'Total' AND ( O.SEV1 > 0 OR O.SEV2 >0 
                       OR O.SEV3 > 0 OR  O.SEV4 >0 )   
ORDER BY O.RCYC_NAME, O.RC_NUM
