SELECT
    R.RCYC_NAME AS CYCLE,
    R.SEV_NAME,
    COALESCE(New.BUG_COUNT, 0) AS New,
    COALESCE(Opened.BUG_COUNT, 0) AS Opened,
    COALESCE(Fixed.BUG_COUNT, 0) AS Fixed,
    COALESCE(Awaiting.BUG_COUNT, 0) AS Awaiting,
    COALESCE(Monitor.BUG_COUNT, 0) AS Monitor,
    COALESCE(Reopen.BUG_COUNT, 0) AS Reopen,
    COALESCE(Deferred.BUG_COUNT, 0) AS Deferred,
    COALESCE(Rejected.BUG_COUNT, 0) AS Rejected,
    COALESCE(Closed.BUG_COUNT, 0) AS Closed,
    COALESCE(Total.BUG_COUNT, 0) AS Total
FROM
(    
    SELECT
        SEV.SEV_NUM,
        SEV.SEV_NAME,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME    
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    CROSS JOIN
    (
        SELECT 1 AS SEV_NUM, '1 - Showstopper' AS SEV_NAME
        UNION ALL
        SELECT 2 AS SEV_NUM, '2 - Critical' AS SEV_NAME
        UNION ALL
        SELECT 3 AS SEV_NUM, '3 - Non-critical' AS SEV_NAME
        UNION ALL
        SELECT 4 AS SEV_NUM, '4 - Live with' AS SEV_NAME
    ) AS SEV    
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) R
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='New'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS New ON New.REL_ID=R.REL_ID AND New.RCYC_NAME=R.RCYC_NAME AND New.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS IN ('Open', 'Opened')
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Opened ON Opened.REL_ID=R.REL_ID AND Opened.RCYC_NAME=R.RCYC_NAME AND Opened.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Fixed'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Fixed ON Fixed.REL_ID=R.REL_ID AND Fixed.RCYC_NAME=R.RCYC_NAME AND Fixed.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Awaiting Retest'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Awaiting ON Awaiting.REL_ID=R.REL_ID AND Awaiting.RCYC_NAME=R.RCYC_NAME AND Awaiting.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Monitor'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Monitor ON Monitor.REL_ID=R.REL_ID AND Monitor.RCYC_NAME=R.RCYC_NAME AND Monitor.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Reopen'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Reopen ON Reopen.REL_ID=R.REL_ID AND Reopen.RCYC_NAME=R.RCYC_NAME AND Reopen.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Deferred'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Deferred ON Deferred.REL_ID=R.REL_ID AND Deferred.RCYC_NAME=R.RCYC_NAME AND Deferred.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Rejected'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Rejected ON Rejected.REL_ID=R.REL_ID AND Rejected.RCYC_NAME=R.RCYC_NAME AND Rejected.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS='Closed'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Closed ON Closed.REL_ID=R.REL_ID AND Closed.RCYC_NAME=R.RCYC_NAME AND Closed.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_DETECTED_IN_RCYC=RELEASE_CYCLES.RCYC_ID
            AND BG_STATUS IN ('New', 'Opened', 'Fixed', 'Awaiting Retest', 'Monitor', 'Reopen', 'Deferred', 'Rejected', 'Closed')
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS Total ON Total.REL_ID=R.REL_ID AND Total.RCYC_NAME=R.RCYC_NAME AND Total.SEVERITY=R.SEV_NUM
ORDER BY R.RCYC_NAME, R.SEV_NUM
