SELECT
    'Total Number of Variances ' AS Label,    
    O.SIT,
    O.UAT,        
    CASE WHEN O.SIT + O.UAT = 0 THEN 0 ELSE CAST(O.SIT AS FLOAT) / (O.SIT + O.UAT) END AS SIT_EFFECTIVENESS
FROM
(
    SELECT
        COALESCE(SIT.BUG_COUNT, 0) AS SIT,
        COALESCE(UAT.BUG_COUNT, 0) AS UAT
    FROM    
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE
        FROM <DB_NAME>.dbo.RELEASES    
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
    ) AS R
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            BUG.BG_USER_TEMPLATE_10 AS DETECTED_IN_PHASE,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_USER_TEMPLATE_10='SIT'
        GROUP BY RELEASES.REL_ID, BUG.BG_USER_TEMPLATE_10
    ) AS SIT ON SIT.REL_ID=R.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            BUG.BG_USER_TEMPLATE_10 AS DETECTED_IN_PHASE,
            COUNT(*) AS BUG_COUNT
        FROM <DB_NAME>.dbo.BUG
        INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND BUG.BG_USER_TEMPLATE_10='UAT'
        GROUP BY RELEASES.REL_ID, BUG.BG_USER_TEMPLATE_10
    ) AS UAT ON UAT.REL_ID=R.REL_ID
) AS O
