SELECT DISTINCT
    RELEASE_CYCLES.RCYC_NAME as CYCLE
FROM <DB_NAME>.dbo.RELEASES    
INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
WHERE RELEASES.REL_ID=<SelectedReleaseID>
ORDER BY RELEASE_CYCLES.RCYC_NAME