SELECT 'Created' AS Label, COUNT(*) AS Value
FROM <DB_NAME>.dbo.BUG
INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID=<SelectedReleaseID>
    AND CAST(BG_DETECTION_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND (BG_CLOSING_DATE IS NULL OR CAST(BG_CLOSING_DATE AS DATE)<>CAST(GETDATE() AS DATE))
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')

UNION ALL

SELECT 'Closed' AS Label, COUNT(*) AS Value
FROM <DB_NAME>.dbo.BUG
INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID=<SelectedReleaseID>
    AND CAST(BG_CLOSING_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND (BG_DETECTION_DATE IS NULL OR CAST(BG_DETECTION_DATE AS DATE)<>CAST(GETDATE() AS DATE))
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')

UNION ALL

SELECT 'Opened & Closed on Same Day' AS Label, COUNT(*) AS Value
FROM <DB_NAME>.dbo.BUG
INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID=<SelectedReleaseID>
    AND CAST(BG_DETECTION_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND CAST(BG_CLOSING_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
