/*
SELECT  DOMAIN_NAME, PROJECT_NAME, DB_NAME, LAST_TOUCH_TIME
FROM qcsiteadmin_ALM125_db.dbo.projects
WHERE PR_IS_ACTIVE='Y'
AND DOMAIN_NAME IN ('MLIDT')
order by DOMAIN_NAME,PROJECT_NAME
*/


--PROJECT NAME
SELECT 
    REL_ID, 
    REL_NAME
FROM mlidt_deposits_f19_db.dbo.RELEASES
WHERE REL_NAME LIKE '%1986%'
ORDER BY REL_NAME





--CYCLE/SPRINT
--TARGET SCHEDULE
SELECT
    RCYC_NAME,
    RCYC_START_DATE AS PLANNED_START_DATE,
    RCYC_END_DATE AS PLANNED_END_DATE
FROM mlidt_deposits_f19_db.dbo.RELEASE_CYCLES
WHERE RCYC_PARENT_ID=1051

SELECT
    RELEASE_CYCLES.RCYC_NAME,
    CAST(RELEASE_CYCLES.RCYC_START_DATE AS DATE) AS PLANNED_START_DATE,
    '' AS ACTUAL_START_DATE,
    CAST(RELEASE_CYCLES.RCYC_END_DATE AS DATE) AS PLANNED_END_DATE,
    '' AS ACTUAL_END_DATE
FROM <DB_NAME>.dbo.RELEASES    
INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
WHERE RELEASES.REL_ID='<SelectedReleaseID>'
ORDER BY RELEASE_CYCLES.RCYC_NAME


SELECT DISTINCT
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS Project,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME,
    RUN.RN_STATUS,
    COUNT(RUN.RN_TEST_ID)
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
LEFT JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
WHERE RELEASES.REL_ID IN (1051)
    AND RUN.RN_TEST_ID IS NOT NULL
    --AND TEST.TS_USER_TEMPLATE_13 <> 'Y'
GROUP BY RELEASES.REL_ID, RELEASES.REL_NAME, RELEASES.REL_USER_TEMPLATE_01, CAST(RELEASES.REL_END_DATE AS DATE), RELEASE_CYCLES.RCYC_NAME, RUN.RN_STATUS



--Daily
--TEST COVERAGE
SELECT
    1 AS SortOrder,
    'Total Executed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Passed', 'Failed', 'Not Completed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    2 AS SortOrder,
    'Passed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Passed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    3 AS SortOrder,
    'Failed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Failed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    4 AS SortOrder,
    'Not Completed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Not Completed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    5 AS SortOrder,
    'Blocked' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Blocked')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    6 AS SortOrder,
    'No Run' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('No Run')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    7 AS SortOrder,
    'N/A (Descoped)' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('N/A')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
        AND R.RN_EXECUTION_DATE=GET_DATE()
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051







--CUMULATIVE
--TEST COVERAGE
SELECT
    1 AS SortOrder,
    'Total Executed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Passed', 'Failed', 'Not Completed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    2 AS SortOrder,
    'Passed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Passed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    3 AS SortOrder,
    'Failed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Failed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    4 AS SortOrder,
    'Not Completed' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Not Completed')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    5 AS SortOrder,
    'Blocked' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('Blocked')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    6 AS SortOrder,
    'No Run' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('No Run')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051


UNION ALL


SELECT
    7 AS SortOrder,
    'N/A (Descoped)' AS Status,
    RELEASES.REL_ID,
    RELEASES.REL_NAME,
    RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
    CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
    RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
    COALESCE(AUTOMATED, 0) AS AUTOMATED,
    COALESCE(MANUAL, 0) AS MANUAL
FROM mlidt_deposits_f19_db.dbo.RELEASES
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
LEFT JOIN
(
    SELECT
        R.REL_ID,
        R.REL_NAME,
        R.REL_USER_TEMPLATE_01,
        R.REL_END_DATE,
        R.RCYC_NAME,
        SUM(CASE WHEN AUTOMATION='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
        SUM(CASE wHEN AUTOMATION<>'Y' THEN 1 ELSE 0 END) AS MANUAL
    FROM
    (
        SELECT
            RELEASES.REL_ID,
            RELEASES.REL_NAME,
            RELEASES.REL_USER_TEMPLATE_01,
            CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
            RELEASE_CYCLES.RCYC_NAME,
            RUN.RN_TEST_ID,
            TEST.TS_EXEC_STATUS,
            LEFT(TEST.TS_USER_TEMPLATE_12, 1) AS AUTOMATION,
            CAST(RUN.RN_EXECUTION_DATE AS DATE) AS RN_EXECUTION_DATE,
            RUN.RN_EXECUTION_TIME,
            ROW_NUMBER() OVER(PARTITION BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME,RUN.RN_TEST_ID ORDER BY RUN.RN_EXECUTION_DATE DESC, RUN.RN_EXECUTION_TIME DESC) AS ROW_NUM
        FROM mlidt_deposits_f19_db.dbo.RELEASES
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.RUN ON RN_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN mlidt_deposits_f19_db.dbo.TEST ON TEST.TS_TEST_ID=RUN.RN_TEST_ID
        WHERE RUN.RN_RUN_ID IS NOT NULL
            AND RUN.RN_TEST_ID IS NOT NULL
            AND TEST.TS_RESPONSIBLE IS NOT NULL
            AND TEST.TS_EXEC_STATUS IN ('N/A')
            AND RELEASES.REL_ID=1051
    ) AS R
    WHERE R.ROW_NUM=1
    GROUP BY REL_ID,REL_NAME,REL_USER_TEMPLATE_01,REL_END_DATE,RCYC_NAME
) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
WHERE RELEASES.REL_ID=1051





--Imran to come back on the Automation flag.


--env downtime. Imran to let me know later on how this works
--To be done manually for now. 


SELECT
    BUG.BG_USER_TEMPLATE_13, /*Defect.Application Under Test*/
    BUG.BG_DETECTION_DATE, /*Defect.Detected on Date*/
    BUG.BG_USER_TEMPLATE_12, /*Defect.Fixed Date*/
    COALESCE(BUG.BG_USER_TEMPLATE_12,GETDATE()),
    *
FROM mlidt_deposits_f19_db.dbo.BUG 
WHERE bg_bug_id=1467





--Daily variance created/closed
SELECT 'Created' AS Label, COUNT(*) AS Value
FROM mlidt_deposits_f19_db.dbo.BUG
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID IN (1051)
    AND CAST(BG_DETECTION_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND CAST(BG_CLOSING_DATE AS DATE) <> CAST(GETDATE() AS DATE)
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')

UNION ALL

SELECT 'Closed' AS Label, COUNT(*) AS Value
FROM mlidt_deposits_f19_db.dbo.BUG
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID IN (1051)
    AND CAST(BG_CLOSING_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND CAST(BG_DETECTION_DATE AS DATE) <> CAST(GETDATE() AS DATE)
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')

UNION ALL

SELECT 'Opened & Closed on Same Day' AS Label, COUNT(*) AS Value
FROM mlidt_deposits_f19_db.dbo.BUG
INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
WHERE RELEASES.REL_ID IN (1051)
    AND CAST(BG_DETECTION_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND CAST(BG_CLOSING_DATE AS DATE)=CAST(GETDATE() AS DATE)
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')

    


--CUMULATIVE VARIANCES BY SEVERITY AND STATUS           
SELECT
    R.SEV_NUM,
    R.SEV_NAME,
    R.REL_ID,
    R.REL_NAME,
    R.REL_USER_TEMPLATE_01,
    R.REL_END_DATE,
    R.RCYC_NAME,
    COALESCE(New.BUG_COUNT, 0) AS New,
    COALESCE(Opened.BUG_COUNT, 0) AS Opened,
    COALESCE(Fixed.BUG_COUNT, 0) AS Fixed,
    COALESCE(Awaiting.BUG_COUNT, 0) AS Awaiting,
    COALESCE(Monitor.BUG_COUNT, 0) AS Monitor,
    COALESCE(Reopen.BUG_COUNT, 0) AS Reopen,
    COALESCE(Deferred.BUG_COUNT, 0) AS Deferred,
    COALESCE(Rejected.BUG_COUNT, 0) AS Rejected,
    COALESCE(Closed.BUG_COUNT, 0) AS Closed
FROM
(    
    SELECT
        SEV.SEV_NUM,
        SEV.SEV_NAME,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME    
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    CROSS JOIN
    (
        SELECT 1 AS SEV_NUM, '1 - Showstopper' AS SEV_NAME
        UNION ALL
        SELECT 2 AS SEV_NUM, '2 - Critical' AS SEV_NAME
        UNION ALL
        SELECT 3 AS SEV_NUM, '3 - Non-critical' AS SEV_NAME
        UNION ALL
        SELECT 4 AS SEV_NUM, '4 - Live with' AS SEV_NAME
    ) AS SEV    
    WHERE RELEASES.REL_ID=1051
) R
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='New'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS New ON New.REL_ID=R.REL_ID AND New.RCYC_NAME=R.RCYC_NAME AND New.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Opened'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Opened ON Opened.REL_ID=R.REL_ID AND Opened.RCYC_NAME=R.RCYC_NAME AND Opened.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Fixed'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Fixed ON Fixed.REL_ID=R.REL_ID AND Fixed.RCYC_NAME=R.RCYC_NAME AND Fixed.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Awaiting Retest'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Awaiting ON Awaiting.REL_ID=R.REL_ID AND Awaiting.RCYC_NAME=R.RCYC_NAME AND Awaiting.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Monitor'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Monitor ON Monitor.REL_ID=R.REL_ID AND Monitor.RCYC_NAME=R.RCYC_NAME AND Monitor.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Reopen'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Reopen ON Reopen.REL_ID=R.REL_ID AND Reopen.RCYC_NAME=R.RCYC_NAME AND Reopen.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Deferred'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Deferred ON Deferred.REL_ID=R.REL_ID AND Deferred.RCYC_NAME=R.RCYC_NAME AND Deferred.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Rejected'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Rejected ON Rejected.REL_ID=R.REL_ID AND Rejected.RCYC_NAME=R.RCYC_NAME AND Rejected.SEVERITY=R.SEV_NUM
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND BG_STATUS='Closed'
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=1051
) AS Closed ON Closed.REL_ID=R.REL_ID AND Closed.RCYC_NAME=R.RCYC_NAME AND Closed.SEVERITY=R.SEV_NUM
ORDER BY R.RCYC_NAME, R.SEV_NUM




 




--CUMULATIVE VARIANCES BY ROOT CAUSE AND SEVERITY            
SELECT
    R.RC_NUM,
    R.ROOTCAUSE,
    R.REL_ID,
    R.REL_NAME,
    R.PROJECT,
    R.REL_END_DATE,
    R.RCYC_NAME,
    COALESCE(SEV1.BUG_COUNT, 0) AS SEV1,
    COALESCE(SEV2.BUG_COUNT, 0) AS SEV2,
    COALESCE(SEV3.BUG_COUNT, 0) AS SEV3,
    COALESCE(SEV4.BUG_COUNT, 0) AS SEV4
FROM    
(
    SELECT
        ROOT_CAUSES.RC_NUM,
        ROOT_CAUSES.ROOTCAUSE,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME    
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    CROSS JOIN
    (
        SELECT 1 AS RC_NUM, 'Code' AS ROOTCAUSE
        UNION ALL
        SELECT 2 AS RC_NUM, 'Requirements' AS ROOTCAUSE
        UNION ALL
        SELECT 3 AS RC_NUM, 'Data' AS ROOTCAUSE
        UNION ALL
        SELECT 4 AS RC_NUM, 'Test Environment' AS ROOTCAUSE
        UNION ALL
        SELECT 5 AS RC_NUM, 'Not Yet Analyzed' AS ROOTCAUSE
        UNION ALL
        SELECT 6 AS RC_NUM, 'Other' AS ROOTCAUSE
    ) AS ROOT_CAUSES    
    WHERE RELEASES.REL_ID=1051
) AS R
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.ROOTCAUSE,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND LEFT(BG_SEVERITY, 1)=1
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
    WHERE RELEASES.REL_ID=1051
) AS SEV1 ON SEV1.REL_ID=R.REL_ID AND SEV1.RCYC_NAME=R.RCYC_NAME AND SEV1.ROOTCAUSE=R.ROOTCAUSE
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.ROOTCAUSE,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND LEFT(BG_SEVERITY, 1)=2
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
    WHERE RELEASES.REL_ID=1051
) AS SEV2 ON SEV2.REL_ID=R.REL_ID AND SEV2.RCYC_NAME=R.RCYC_NAME AND SEV2.ROOTCAUSE=R.ROOTCAUSE
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.ROOTCAUSE,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND LEFT(BG_SEVERITY, 1)=3
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
    WHERE RELEASES.REL_ID=1051
) AS SEV3 ON SEV3.REL_ID=R.REL_ID AND SEV3.RCYC_NAME=R.RCYC_NAME AND SEV3.ROOTCAUSE=R.ROOTCAUSE
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        RELEASE_CYCLES.RCYC_NAME,
        B.ROOTCAUSE,
        B.SEVERITY,
        B.BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.RELEASES
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID,
            RELEASE_CYCLES.RCYC_NAME,
            BUG.BG_USER_TEMPLATE_01 AS ROOTCAUSE,
            LEFT(BG_SEVERITY, 1) AS SEVERITY,
            COUNT(*) AS BUG_COUNT
        FROM mlidt_deposits_f19_db.dbo.BUG
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
        INNER JOIN mlidt_deposits_f19_db.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        WHERE RELEASES.REL_ID=1051
            AND LEFT(BG_SEVERITY, 1)=4
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_NAME, BUG.BG_USER_TEMPLATE_01, LEFT(BG_SEVERITY, 1)
    ) AS B ON B.REL_ID=RELEASES.REL_ID AND B.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME 
    WHERE RELEASES.REL_ID=1051
) AS SEV4 ON SEV4.REL_ID=R.REL_ID AND SEV4.RCYC_NAME=R.RCYC_NAME AND SEV4.ROOTCAUSE=R.ROOTCAUSE
ORDER BY R.RCYC_NAME, R.RC_NUM







---Assigned Var. by Department  
--is manual entry for now


--CUMULATIVE SIT EFFECTIVENESS*       
SELECT
    'Total Number of Variances ' AS Label,    
    COALESCE(SIT.BUG_COUNT, 0) AS SIT,
    COALESCE(UAT.BUG_COUNT, 0) AS UAT,
    CASE WHEN SIT + UAT = 0 THEN 0 ELSE CAST(SIT AS FLOAT) / (SIT + UAT) AS SIT_EFFECTIVENESS
FROM    
(
    SELECT
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE
    FROM mlidt_deposits_f19_db.dbo.RELEASES    
    WHERE RELEASES.REL_ID=1051        
) AS R
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        BUG.BG_USER_TEMPLATE_10 AS DETECTED_IN_PHASE,
        COUNT(*) AS BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.BUG
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
    WHERE BUG.BG_DETECTED_IN_REL=1051
        AND BUG.BG_USER_TEMPLATE_10='SIT'
    GROUP BY RELEASES.REL_ID, BUG.BG_USER_TEMPLATE_10
) AS SIT ON SIT.REL_ID=R.REL_ID
LEFT JOIN
(
    SELECT
        RELEASES.REL_ID,
        BUG.BG_USER_TEMPLATE_10 AS DETECTED_IN_PHASE,
        COUNT(*) AS BUG_COUNT
    FROM mlidt_deposits_f19_db.dbo.BUG
    INNER JOIN mlidt_deposits_f19_db.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
    WHERE BUG.BG_DETECTED_IN_REL=1051
        AND BUG.BG_USER_TEMPLATE_10='UAT'
    GROUP BY RELEASES.REL_ID, BUG.BG_USER_TEMPLATE_10
) AS UAT ON UAT.REL_ID=R.REL_ID
