SELECT RCYC_NAME as CYCLE,
    CASE
        WHEN DATEDIFF(DAY, CAST(BUG.BG_DETECTION_DATE AS DATE), CAST(ISNULL(BUG.BG_CLOSING_DATE, GETDATE()) AS DATE)) <= 4 THEN '0 - 4 days'
        ELSE '> 4 Days'
    END AS AgingCategory,
    COUNT(*) AS Count
FROM <DB_NAME>.dbo.BUG
INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID = BUG.BG_DETECTED_IN_REL
INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID = RELEASES.REL_ID
WHERE RELEASES.REL_ID = <SelectedReleaseID>
    AND RELEASE_CYCLES.RCYC_ID = BUG.BG_DETECTED_IN_RCYC
    AND LEFT(BG_SEVERITY, 1) = '1'
    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
GROUP BY RCYC_NAME , 
    CASE
        WHEN DATEDIFF(DAY, CAST(BUG.BG_DETECTION_DATE AS DATE), CAST(ISNULL(BUG.BG_CLOSING_DATE, GETDATE()) AS DATE)) <= 4 THEN '0 - 4 days'
        ELSE '> 4 Days'
    END
    UNION ALL
    SELECT '' as CYCLE, '0 - 4 days' as AgingCategory, 0 as Count
    UNION ALL
    SELECT '' as CYCLE, '> 4 Days' as AgingCategory, 0 as Count
-- SELECT
--     BUG.BG_BUG_ID,
--     BUG.BG_STATUS,
--     CAST(BUG.BG_DETECTION_DATE AS DATE) AS BG_DETECTION_DATE,
--     CAST(BUG.BG_CLOSING_DATE AS DATE) AS BG_CLOSING_DATE,        
--     0 AS NETWORKDAYS,
--     RCYC_NAME
-- FROM <DB_NAME>.dbo.BUG
-- INNER JOIN <DB_NAME>.dbo.RELEASES ON RELEASES.REL_ID=BUG.BG_DETECTED_IN_REL
-- INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
-- WHERE RELEASES.REL_ID=<SelectedReleaseID>
--     AND RELEASE_CYCLES.RCYC_ID=BUG.BG_DETECTED_IN_RCYC
--    AND LEFT(BG_SEVERITY,1)=1
--    AND BUG.BG_USER_TEMPLATE_10 IN ('SIT', 'UAT')
