SELECT
    RELEASE_CYCLES.RCYC_NAME as CYCLE,
    CAST(RELEASE_CYCLES.RCYC_START_DATE AS DATE) AS PLANNED_START_DATE,
    '' AS ACTUAL_START_DATE,
    CAST(RELEASE_CYCLES.RCYC_END_DATE AS DATE) AS PLANNED_END_DATE,
    '' AS ACTUAL_END_DATE
FROM <DB_NAME>.dbo.RELEASES    
INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
WHERE RELEASES.REL_ID=<SelectedReleaseID>
ORDER BY RELEASE_CYCLES.RCYC_NAME