SELECT RELEASE_CYCLES.RCYC_NAME as CYCLE,TC_TESTER_NAME, TC_STATUS  ,CAST(TC_EXEC_DATE AS DATE) as EXEC_DATE  ,count(*) as COUNT
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
    INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
    INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
    AND CAST(TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
      GROUP BY RELEASE_CYCLES.RCYC_NAME,TC_TESTER_NAME, TC_STATUS  ,TC_EXEC_DATE