SELECT
    CYCLE,
    Status,
    MANUAL,
    AUTOMATED,CAST(EXEC_DATE AS DATE) as EXECION_DATE
FROM
(
    SELECT
        1 AS SortOrder,
        'Total Executed' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS IN ('Passed', 'Failed', 'Not Completed')
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE 
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        2 AS SortOrder,
        'Passed' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='Passed'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        3 AS SortOrder,
        'Failed' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='Failed'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        4 AS SortOrder,
        'Not Completed' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='Not Completed'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        5 AS SortOrder,
        'Blocked' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='Blocked'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        6 AS SortOrder,
        'No Run' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='No Run'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>


    UNION ALL


    SELECT
        7 AS SortOrder,
        'N/A (Descoped)' AS Status,
        RELEASES.REL_ID,
        RELEASES.REL_NAME,
        RELEASES.REL_USER_TEMPLATE_01 AS PROJECT,
        CAST(RELEASES.REL_END_DATE AS DATE) AS REL_END_DATE,
        RELEASE_CYCLES.RCYC_NAME AS CYCLE, 
        COALESCE(AUTOMATED, 0) AS AUTOMATED,
        COALESCE(MANUAL, 0) AS MANUAL,EXEC_DATE
    FROM <DB_NAME>.dbo.RELEASES
    INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
    LEFT JOIN
    (
        SELECT
            RELEASES.REL_ID, 
            RELEASE_CYCLES.RCYC_ID,
            RELEASE_CYCLES.RCYC_NAME,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)='Y' THEN 1 ELSE 0 END) AS AUTOMATED,
            SUM(CASE WHEN LEFT(TEST.TS_USER_TEMPLATE_12, 1)<>'Y' THEN 1 ELSE 0 END) AS MANUAL,TESTCYCL.TC_EXEC_DATE as EXEC_DATE
        FROM <DB_NAME>.dbo.RELEASES
        INNER JOIN <DB_NAME>.dbo.RELEASE_CYCLES ON RELEASE_CYCLES.RCYC_PARENT_ID=RELEASES.REL_ID
        INNER JOIN <DB_NAME>.dbo.CYCLE ON CYCLE.CY_ASSIGN_RCYC=RELEASE_CYCLES.RCYC_ID
        INNER JOIN <DB_NAME>.dbo.TESTCYCL ON TESTCYCL.TC_CYCLE_ID=CYCLE.CY_CYCLE_ID
        INNER JOIN <DB_NAME>.dbo.TEST ON TEST.TS_TEST_ID=TESTCYCL.TC_TEST_ID
        WHERE RELEASES.REL_ID=<SelectedReleaseID>
            AND TESTCYCL.TC_STATUS='N/A'
            --AND CAST(TESTCYCL.TC_EXEC_DATE AS DATE)=CAST(GETDATE() AS DATE)
        GROUP BY RELEASES.REL_ID, RELEASE_CYCLES.RCYC_ID, RELEASE_CYCLES.RCYC_NAME,TESTCYCL.TC_EXEC_DATE
    ) AS R ON R.REL_ID=RELEASES.REL_ID AND R.RCYC_NAME=RELEASE_CYCLES.RCYC_NAME
    WHERE RELEASES.REL_ID=<SelectedReleaseID>
) AS O WHERE  O.EXEC_DATE <>'' and Status<>'Total Executed'
ORDER BY O.Cycle, O.SortOrder
